Basics_Django/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('todo/', include('todo_list.urls'))
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("hima", views.hima, name='hima'),
    path("bindu", views.bindu, name='bindu'),
    #when ever a string with anyvalue is called then someone function will exicuted and it will pass name parameter from <str > to the someone method 
    path("<str:name>", views.somename, name='somename')
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

todo_list/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

todo_list/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
# def index(request):
#     return HttpResponse('Hello')

def hima(request):
    return HttpResponse('Hello Hima')

def bindu(request):
    return HttpResponse('Hello Bindu')

# dynamic name template syntax
# def somename(request, name):
#     return HttpResponse(f'Hello, {name.upper()}')

# Insted of retuting only a single string we can retrun a full html page or some python code ect
# insted of returing a single quote in default route i.e, index from above function
def index(request):
    return render(request, 'hello/index.html')

# Let's see rendering a page with some additional context like below
def somename(request, name):
    return render(request, 'hello/someone.html', {
        'name': name.upper()
    })

newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html', {
        'newyear': now.month == 1 and now.day == 1
    })

todo_list/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def index(request):
    # session uses to check if the variable is already exist in the browser (only visibale on same session / like session storage in html)
    if "todo_list_items" not in request.session:
        request.session["todo_list_items"] = []

    return render(request, 'todo_list/index.html', {
        "tasks" : request.session["todo_list_items"]
    })


# class to represent form from django
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New item")


def add(request):
    if request.method == 'POST':
        # above if is true we are storing all the post data into form variable
        form = NewTaskForm(request.POST)
        if form.is_valid():
            # task is the data in above class i.e; the form data
            task_created = form.cleaned_data["task"]
            request.session["todo_list_items"] += [task_created]
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return render(request, 'todo_list/add.html', {
                #have to send existing form data
                "form": form
            })

    return render(request, 'todo_list/add.html', {
        'form': NewTaskForm()
    })

hello/templates/hello/index.html
<!Doctype HTML>
<html>
    <head>
        <title>index page</title>
    </head>
    <body>
        <h1>Index page</h1>
    </body>
</html>

hello/templates/hello/someone.html
<!Doctype HTML>
<html>
    <head>
        <title>index page</title>
    </head>
    <body>
        <!-- name comes from the views.py -->
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!Doctype HTML>
<html>
    <head>
        <title>Is it New Year ?</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- below shows logical operations in html page using django  & newyear variable comes from views.py page-->
        {% if newyear %}
            <h1> YES </h1>
        {% else %}
            <h1> NO </h1>
        {% endif %}
    </body>
</html>

todo_list/templates/todo_list/add.html
{% extends "todo_list/layout.html" %}

{% block body %}
<h1>
    Add Item to list
</h1>
<form action="{% url 'todo:add' %}" method="POST">
    <!-- without csrf_token we will get 403 forbidden error. csrf_token is available in settings.py -->
    {% csrf_token %}
    <!-- in urls.py we gave the name as index and todo is the app_name specificied in urls file-->
    <a href="{% url 'todo:index' %}">Back to view tasks</a>
    <!-- form comes from views.py -->
    {{ form }}
    <!-- below is the static form  -->
    <!-- <input type="text" name="additem" placeholder="Enter item to be added" value=""> -->
    <input type="submit">
</form>
{% endblock %}

todo_list/templates/todo_list/index.html
{% extends "todo_list/layout.html" %}

{% block body %}
<h1>Todo list items: </h1>
<!-- in urls.py we gave the name as add and todo is the app_name specificied in urls file -- this is equla to a tag href= /todo-list/add  -->
<a href="{% url 'todo:add' %}">Add new item</a>
<ul>
    {% for item in tasks %}
    <li>{{ item }}</li>
    {% empty %}
    <li> No tasks to view</li>
    {% endfor %}
</ul>
{% endblock %}

todo_list/templates/todo_list/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>